### ISSUE TITLE
Autosize no input de mensagem

### ISSUE THREAD

**Issue by joaom00** [pablowinck/next-chat-group#12]
Acho que adicionar o autosize no input seria uma boa, percebi que o Discord e o Whatsapp fazem isso, pois se o usuário for digitar uma mensagem grande não fica tudo em uma linha e também permiti enviar mensagens com quebra de linha.

https://user-images.githubusercontent.com/48808846/151978928-5463264e-5a6e-444e-bc4e-203cf36a9305.mp4

**Comment by pablowinck** [comment]
Po acho maneiro demais, não tinha pensado nisso. Podemos botar o input como textarea, só temos que ver como vamos fazer com o button:
* manter o button de enviar em cima (como o discord faz),
* se vamos fazer o resizing dele também (que acho inviável), 
* ou se deixaremos o button de enviar em baixo (como o whatsapp faz)

**Comment by joaom00** [comment]
Gostei de deixar o botão em baixo, acho que é a melhor opção
